### PR TITLE
Test in parallel

### PR DESCRIPTION
**Pull request by thedrow**
This should speed up testing times.

### CODE REVIEW

**Comment by thedrow** [comment]
Seems like testing in parallel isn't possible with the current test suite.
Any idea why?

**Comment by Lukasa** [comment]
So I *don't* know why, and it's been bothering me for a little while. pytest-xdist and pytest-cov seem to have started misbehaving in ways I don't fully understand, which led to me unparallelising a whole bunch of tests rather than dig into the problem.

You're certainly welcome to dig in to try to discover it, but I don't consider it to be an enormous priority for brotlipy: there simply aren't that many tests.

**Comment by thedrow** [comment]
But they take way too long.

**Comment by Lukasa** [comment]
Yeah, I'm not disagreeing. But the burden of those tests is not that high. This module has relatively low churn because there is just very little code in it, so the development cost of slow-ish tests isn't very high. Like I said, ultimately I'm just one person, and this is low down my priority list.

*You*, however, are free to spend your time however you wish, and if parallelising these tsts is how you wish to spend it then more power to you.

**Comment by thedrow** [comment]
I'm going to close this for now and open an issue instead. We'll see if I can figure it out.

**Pull request closed without merging**
