### PR TITLE
Use release 0.3.0 of brotli.

### PR DESCRIPTION
**Pull request by ionelmc**
This seems to solve #17

### CODE REVIEW

**Comment by ionelmc** [comment]
0.3.0 being this: https://github.com/google/brotli/releases/tag/v0.3.0

**Comment by Lukasa** [comment]
@ionelmc Heh, saved me the work! Thanks!

**Comment by Lukasa** [comment]
I'll push a new formal release of this shortly.

**Comment by ionelmc** [comment]
Thanks.

**Pull request merged**
